#!/usr/bin/env python
"""
    ASCII Animācija. Ielādē monitorā.
"""
from time import sleep
from os import system

system('clear')
print(" ________________ ")
print("|                |")
print("|                |")
print("|                |")
print("|                |")
print("|________________|")
print("        ||        ")
print("      _/__\_      ")
sleep(0.9)

system('clear')
print(" ________________ ")
print("|                |")
print("|                |")
print("|      (         |")
print("|                |")
print("|________________|")
print("        ||        ")
print("      _/__\_      ")
sleep(0.9)

system('clear')
print(" ________________ ")
print("|                |")
print("|       _        |")
print("|      (         |")
print("|                |")
print("|________________|")
print("        ||        ")
print("      _/__\_      ")
sleep(0.9)

system('clear')
print(" ________________ ")
print("|                |")
print("|       _        |")
print("|        )       |")
print("|                |")
print("|________________|")
print("        ||        ")
print("      _/__\_      ")
sleep(0.9)

system('clear')
print(" ________________ ")
print("|                |")
print("|                |")
print("|        _)      |")
print("|                |")
print("|________________|")
print("        ||        ")
print("      _/__\_      ")
sleep(0.6)

system('clear')
print(" ________________ ")
print("|                |")
print("|                |")
print("|       (_)      |")
print("|                |")
print("|________________|")
print("        ||        ")
print("      _/__\_      ")
sleep(0.6)

system('clear')
print(" ________________ ")
print("|                |")
print("|        _       |")
print("|       (_)      |")
print("|                |")
print("|________________|")
print("        ||        ")
print("      _/__\_      ")
sleep(0.6)

system('clear')
print(" ________________ ")
print("|                |")
print("|                |")
print("|       Hi!      |")
print("|                |")
print("|________________|")
print("        ||        ")
print("      _/__\_      ")
sleep(0.9)
