#!/usr/bin/env python
"""
    ASCII Animācija. Dūmi no mājas skursteņa.
"""
from time import sleep
from os import system

system('clear')
print("                           ")
print("                           ")
print("                           ")
print("      _|=|__________       ")
print("     /              \\     ")
print("    /                \\    ")
print("   /__________________\\   ")
print("    ||  || /--\\ ||  ||    ")
print("    ||[]|| | .| ||[]||     ")
print("  ()||__||_|__|_||__||()   ")
print(" ( )|-|-|-|====|-|-|-|( )  ")
print(" ^^^^^^^^^^====^^^^^^^^^^^ ")
sleep(1.5)

system('clear')
print("                          ")
print("                          ")
print("       (                  ")
print("     _|=|__________       ")
print("    /              \\     ")
print("   /                \\    ")
print("  /__________________\\   ")
print("   ||  || /--\\ ||  ||     ")
print("   ||[]|| | .| ||[]||     ")
print(" ()||__||_|__|_||__||()   ")
print("( )|-|-|-|====|-|-|-|( )  ")
print("^^^^^^^^^^====^^^^^^^^^^^ ")
sleep(1.5)

system('clear')
print("                          ")
print("       (                  ")
print("       )                  ")
print("     _|=|__________       ")
print("    /              \\     ")
print("   /                \\    ")
print("  /__________________\\   ")
print("   ||  || /--\\ ||  ||    ")
print("   ||[]|| | .| ||[]||     ")
print(" ()||__||_|__|_||__||()   ")
print("( )|-|-|-|====|-|-|-|( )  ")
print("^^^^^^^^^^====^^^^^^^^^^^ ")
sleep(1.5)

system('clear')
print("      )                   ")
print("       )                  ")
print("                          ")
print("     _|=|__________       ")
print("    /              \\     ")
print("   /                \\    ")
print("  /__________________\\   ")
print("   ||  || /--\\ ||  ||    ")
print("   ||[]|| | .| ||[]||     ")
print(" ()||__||_|__|_||__||()   ")
print("( )|-|-|-|====|-|-|-|( )  ")
print("^^^^^^^^^^====^^^^^^^^^^^ ")
sleep(1)

system('clear')
print("      (                   ")
print("                          ")
print("                          ")
print("     _|=|__________       ")
print("    /              \\     ")
print("   /                \\    ")
print("  /__________________\\   ")
print("   ||  || /--\\ ||  ||    ")
print("   ||[]|| | .| ||[]||     ")
print(" ()||__||_|__|_||__||()   ")
print("( )|-|-|-|====|-|-|-|( )  ")
print("^^^^^^^^^^====^^^^^^^^^^^ ")
sleep(1.5)

system('clear')
print("                          ")
print("                          ")
print("                          ")
print("     _|=|__________       ")
print("    /              \\     ")
print("   /                \\    ")
print("  /__________________\\   ")
print("   ||  || /--\\ ||  ||    ")
print("   ||[]|| | .| ||[]||     ")
print(" ()||__||_|__|_||__||()   ")
print("( )|-|-|-|====|-|-|-|( )  ")
print("^^^^^^^^^^====^^^^^^^^^^^ ")
sleep(1.5)
